stages:
    - test
    - build
    - deploy
    

run-unit-tests:
    stage: test
    image: python:3.12
    script:
        - |
            pip install pytest
            pip install -r ./requirements.txt
        - python -m pytest .system_cars/Tests/unit


run-e2e-tests:
    stage: test
    image: python:3.12
    script:
        - |
            pip install pytest
            pip install gunicorn
            pip install -r ./requirements.txt
        - gunicorn --workers=1 -b=0.0.0.0:8000 --chdir=./system_cars --daemon system_cars.wsgi:application
        - sleep 5
        - python -m pytest .system_cars/Tests/e2e
