stages:
    - test
    - build
    - deploy
    

run-unit-tests:
    stage: test
    image: python:3.10
    script:
        - |
            pip install pytest
            pip install -r ./requirements.txt
        - python -m pytest ./system_cars/Tests/unit


run-e2e-tests:
    stage: test
    image: python:3.12
    script:
        - |
            pip install pytest
            pip install gunicorn
            pip install -r ./requirements.txt
        - gunicorn --workers=1 -b=0.0.0.0:8000 --chdir=./system_cars --daemon system_cars.wsgi:application
        - sleep 5
        - python -m pytest ./system_cars/Tests/e2e


build-prod-image:
    stage: build
    image: docker:dind
    script:
        - docker build -f Dockerfile.prod -t system_cars:latest .
        - docker save system_cars:latest > system_cars.tar
    needs:
        - run-unit-tests
        - run-e2e-tests
    artifacts:
        when: on_success
        expire_in: 10m
        paths:
            - "system_cars.tar"